/* Agar icon reference file */
/* Generated by agarpaint 1.2 */

__BEGIN_DECLS
extern AG_StaticIcon vsIconStamp;
extern AG_StaticIcon vsIconMagnifier;
extern AG_StaticIcon vsIconLayerEditor;
extern AG_StaticIcon vsIconMirror;
extern AG_StaticIcon vsIconFlip;
extern AG_StaticIcon vsIconInvert;
extern AG_StaticIcon vsIconHGrad;
extern AG_StaticIcon vsIconVGrad;
extern AG_StaticIcon vsIconCGrad;
extern AG_StaticIcon vsIconTiling;
extern AG_StaticIcon vsIconSketchProj;
extern AG_StaticIcon vsIconSketch;
extern AG_StaticIcon vsIconSketchAttach;
extern AG_StaticIcon vsIconPixmapResize;
extern AG_StaticIcon vsIconPixmapAttach;
extern AG_StaticIcon vsIconPolygon;
extern AG_StaticIcon vsIconSwap;
extern AG_StaticIcon vsIconControls;
extern AG_StaticIcon vsIconPixmap;
extern AG_StaticIcon vsIconWalkable;
extern AG_StaticIcon vsIconObject;
extern AG_StaticIcon vsIconMap_n0;
extern AG_StaticIcon vsIconDrawing;
extern AG_StaticIcon vsIconTileset;
extern AG_StaticIcon vsIconEdit;
extern AG_StaticIcon vsIconDuplicate;
extern AG_StaticIcon vsIconOrigin;
extern AG_StaticIcon vsIconGrid;
extern AG_StaticIcon vsIconPlay;
extern AG_StaticIcon vsIconPause;
extern AG_StaticIcon vsIconStop;
extern AG_StaticIcon vsIconRewind;
extern AG_StaticIcon vsIconForward;
extern AG_StaticIcon vsIconRewindFrame;
extern AG_StaticIcon vsIconForwardFrame;
extern AG_StaticIcon vsIconFill;
__END_DECLS
